workspace:
  subscription_id: 'a0375d6b-a4f6-4c9e-9054-e9982f6f6765'
  create_workspace: False
  resource_group: 'GPU_Test'
  workspace_name: 'InsuranceImageRecognition'
  location: 'westeu'
  compute_config_target: 'amlcompute'
  compute_name: 'gpu-cluster-NC6'
  vm_size: 'Standard_NC6'
  compute_target: 'bierli011'
  experiment_name: 'test_training'
  dataset_name: 'crash_images'
  dataset_id: ''

conda_environment:
  create_environment: False
  environment_name: 'insurance_image_recog'
  pip_dependencies:
    - 'azureml-defaults'
    - 'torch==1.12.0'
    - 'mlflow==2.0.1'
    - 'torchinfo==1.7.1'
    - 'torchvision==0.13.0'
    - 'azureml-mlflow==1.48.0'
  conda_dependencies:

data_upload:
  upload: False
  path_to_data: 'C:\Users\lbierling\OneDrive - KPMG\Projekte\Versicherung-Fehlererkennung\Project\image_recog_git\image_recog_git\insurance_image_recog\data3'
  target_path: '/data/'
  dataset_name: 'crash_images'
  dataset_description: 'Crash and no crash images for classification'


run_script:
  experiment_name: 'test_training'
  run_source_directory: '../models'
  run_script_file_name: 'model_training.py'
