#TODO tackle class imbalance

create_train_test_dir :
    create_new_dirs : False # Create new train and test dirs based on a random split defined in the model configuration below
    source_path : 'D:\ML\DL\projects\insurance_image_recog\data'
    destination_path : 'D:\ML\DL\projects\insurance_image_recog\data\data_split'

image_path: 'D:\ML\DL\projects\insurance_image_recog\data\data_split'
model_to_use: 'vgg19'
specific_modelName_to_use: 'vgg19'


base_model:
    transformations:
        crop_size: 200
        flip_degrees: 30

vgg19:
    train_verbosity: # what to print during training
        loss: True
        prediction: True
        prediction_probabilities: True
        true_labels: True
        accuracy: True

    validation_verbosity: # what to print during validation
        loss: True
        prediction: True
        prediction_probabilities: True
        true_labels: True
        accuracy: True

    epochs: 50
    batch_size: 16
    learning_rate: 0.0001
    train_backbone_params: True
    train_test_split_ratio: 0.7
    activation_function: 'tanh'
    early_stopping : False
    classifier_layer:
        - classifier_layer_1:
            - 25088
            - 10
            - 0 # Dropout rate

resnet:
    train_verbosity: # what to print during training
        loss: True
        predictions: True
        prediction_probabilities: True
        true_labels: True

    validation_verbosity: # what to print during validation
            loss: True
            predictions: True
            prediction_probabilities: True
            true_labels: True

    epochs: 100
    batch_size: 16
    learning_rate: 0.001
    train_backbone_params: True
    train_test_split_ratio: 0.8
    activation_function: 'tanh'
    classifier_layer:
        - classifier_layer_1:
            - 512
            - 256
            - 0.2 # Dropout rate
        - classifier_layer_2:
            - 256
            - 6
            - 0

custom1:
    epochs: 50
    batch_size: 16
    learning_rate: 0.001
    train_backbone_params: True
    train_test_split_ratio: 0.8
    activation_function: 'tanh'
    classifier_layer:
        - classifier_layer_1:
            - 1600
            - 1024
            - 0.2 # Dropout rate
        - classifier_layer_2:
            - 1024
            - 512
            - 0  # Dropout rate
        - classifier_layer_3:
            - 512
            - 6
            - 0 # Dropout rate
