image_path: 'C:\Users\lbierling\OneDrive - KPMG\Projekte\Versicherung-Fehlererkennung\Project\image_recog_git\image_recog_git\insurance_image_recog\data'

model_to_use: 'vgg19'

base_model:
    transformations:
        crop_size: 200
        flip_degrees: 30

vgg19:
    epochs: 100
    batch_size: 16
    learning_rate: 0.0001
    train_backbone_params: True
    train_test_split_ratio: 0.9
    classifier_layer:
        - classifier_layer_1:
            - 25088
            - 4096
            - 0.2 # Dropout rate
        - classifier_layer_2:
            - 4096
            - 1024
            - 0.2  # Dropout rate
        - classifier_layer_3:
            - 1024
            - 10
            - 0 # Dropout rate

resnet:
    epochs: 100
    batch_size: 16
    learning_rate: 0.001
    train_backbone_params: True
    train_test_split_ratio: 0.8
    classifier_layer:
        - classifier_layer_1:
            - 512
            - 256
            - 0.2 # Dropout rate
        - classifier_layer_2:
            - 256
            - 10
            - 0

custom1:
    epochs: 10
    batch_size: 16
    learning_rate: 0.01
    train_backbone_params: True
    train_test_split_ratio: 0.9
    classifier_dropout_rate : 0.2
    classifier_layer:
        - classifier_layer_1:
            - 120000
            - 4096
            - 0.2 # Dropout rate
        - classifier_layer_2:
            - 4096
            - 1024
            - 0  # Dropout rate
        - classifier_layer_3:
            - 1024
            - 10
            - 0 # Dropout rate
