#TODO tackle class imbalance

image_path: 'D:\ML\DL\projects\insurance_image_recog\data2\data_split'
model_to_use: 'vgg19'

base_model:
    transformations:
        crop_size: 200
        flip_degrees: 30

vgg19:
    epochs: 100
    batch_size: 12
    learning_rate: 0.0001
    train_backbone_params: True
    train_test_split_ratio: 0.7
    activation_function: 'leakyrelu'
    early_stopping : False
    classifier_layer:
        - classifier_layer_1:
            - 25088
            - 4096
            - 0.2 # Dropout rate
        - classifier_layer_2:
            - 4096
            - 1024
            - 0.2  # Dropout rate
        - classifier_layer_3:
            - 1024
            - 5
            - 0 # Dropout rate

resnet:
    epochs: 100
    batch_size: 16
    learning_rate: 0.001
    train_backbone_params: True
    train_test_split_ratio: 0.8
    activation_function: 'tanh'
    classifier_layer:
        - classifier_layer_1:
            - 512
            - 256
            - 0.2 # Dropout rate
        - classifier_layer_2:
            - 256
            - 10
            - 0

custom1:
    epochs: 50
    batch_size: 12
    learning_rate: 0.001
    train_backbone_params: True
    train_test_split_ratio: 0.8
    activation_function: 'tanh'
    classifier_layer:
        - classifier_layer_1:
            - 1600
            - 1024
            - 0.2 # Dropout rate
        - classifier_layer_2:
            - 1024
            - 512
            - 0  # Dropout rate
        - classifier_layer_3:
            - 512
            - 5
            - 0 # Dropout rate
